version: "3.9"

services:
  productsmysql:
    image: mysql:8.0
    container_name: products_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: productsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  productsapi:
    build:
      context: .
      dockerfile: products.Api/Dockerfile
    container_name: products_api
    depends_on:
      - productsmysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=productsmysql;Port=3306;Database=productsdb;User=admin;Password=1234;SslMode=none;
      - Jwt__Key=MiSuperClaveUltraSeguraDeMasDe32Caracteres123!
      - Jwt__Issuer=productosApi
      - Jwt__Audience=productosClient
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AllowedHosts=*
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: always

  adminer:
    image: adminer
    container_name: products_adminer
    restart: always
    depends_on:
      - productsmysql
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=productsmysql

volumes:
  mysql_data:
